version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:12.4-alpine
    networks:
      - default
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - ./local/postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "logging_collector=on", "-c", "log_directory=pg_logs", "-c", "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"]
